version: '3.8'

services:
  mccotter-net-api:
    image: mccotter-api
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 5000:5000
